# ######################################### #
# # MultiWorlds by CraftingDragon007 2020 # #
# ######################################### #

firstrun: true

# Only modify if you want to reset everything.

standardmaxslots: -1

# Standard Maximum pro Welt

enable-spawn-on-join: false

# Ob der Spieler beim joinen zum Spawn teleportiert wird

spawnworld: world

# Die Welt in die Spieler beim joinen kommen.